In [50]:
'''
OBJECTTIVES
- The goal of this project analyse retail sales transaction data to find any revenue trends, product category performances and customer demographic
patters.

'''

'\nOBJECTTIVES\n- The goal of this project analyse retail sales transaction data to find any revenue trends, product category performances and customer demographic\npatters.\n\n'

In [51]:
import pandas as pd
import sqlite3
import plotly.express as px

In [52]:
conn = sqlite3.connect('sales.db')

In [53]:
# Loading retail sales data set from Kaggle

retail_s = pd.read_csv('data/retail_sales_dataset.csv')

In [54]:
retail_s.shape

(1000, 9)

In [55]:
retail_s.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [56]:
retail_s.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [57]:
retail_s.isna().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [58]:
retail_s.duplicated().sum()

np.int64(0)

In [59]:
'''
Findings:
- 1000 tansactions.
- No duplicated rows found.
- No missing values found.
- Date column is in string format so that needs to be changed to date time.
- Column names have spaces.

'''

'\nFindings:\n- 1000 tansactions.\n- No duplicated rows found.\n- No missing values found.\n- Date column is in string format so that needs to be changed to date time.\n- Column names have spaces.\n\n'

In [60]:
retail_s['Date'] = pd.to_datetime(retail_s['Date'])
retail_s.columns = retail_s.columns.str.replace(' ', '_')

In [61]:
retail_s.dtypes

Transaction_ID               int64
Date                datetime64[us]
Customer_ID                    str
Gender                         str
Age                          int64
Product_Category               str
Quantity                     int64
Price_per_Unit               int64
Total_Amount                 int64
dtype: object

In [62]:
retail_s.head()

,Transaction_ID,Date,Customer_ID,Gender,Age,Product_Category,Quantity,Price_per_Unit,Total_Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [63]:
retail_s['month'] = retail_s['Date'].dt.month_name()
retail_s['day'] = retail_s['Date'].dt.day_name()
retail_s['month_val'] = retail_s['Date'].dt.month
retail_s['day_val'] = retail_s['Date'].dt.day_of_week

In [64]:
bins = [0, 25, 35, 45, 55, 100]

labels = [
    '18-25',
    '26-35',
    '36-45',
    '46-55',
    '56+'
]

retail_s['Age_group'] = pd.cut(retail_s['Age'],
                               bins=bins,
                               labels=labels)

In [65]:
retail_s

,Transaction_ID,Date,Customer_ID,Gender,Age,Product_Category,Quantity,Price_per_Unit,Total_Amount,month,day,month_val,day_val,Age_group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,November,Friday,11,4,26-35
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,February,Monday,2,0,26-35
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,January,Friday,1,4,46-55
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,May,Sunday,5,6,36-45
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,May,Saturday,5,5,26-35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,May,Tuesday,5,1,56+
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,November,Friday,11,4,46-55
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,October,Sunday,10,6,18-25
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,December,Tuesday,12,1,36-45
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,April,Wednesday,4,2,46-55

In [66]:
'''
Changes made: 

- Date column has been changed to date time object.
- Column name with spaces have been replaced with '_'.
- Created new columns for day and month name including its numerical value for easier analysis.
- Created new columns for age group for easoer analysis later.

'''

"\nChanges made: \n\n- Date column has been changed to date time object.\n- Column name with spaces have been replaced with '_'.\n- Created new columns for day and month name including its numerical value for easier analysis.\n- Created new columns for age group for easoer analysis later.\n\n"

In [67]:
retail_s.head()

,Transaction_ID,Date,Customer_ID,Gender,Age,Product_Category,Quantity,Price_per_Unit,Total_Amount,month,day,month_val,day_val,Age_group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,November,Friday,11,4,26-35
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,February,Monday,2,0,26-35
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,January,Friday,1,4,46-55
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,May,Sunday,5,6,36-45
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,May,Saturday,5,5,26-35

In [68]:
retail_s.to_sql('initial_data', conn, if_exists='replace', index=False)

1000

In [69]:
tables = pd.read_sql('''
SELECT name
FROM sqlite_master
WHERE type = 'table'
                     ''', conn)
tables

           name
0  initial_data

In [70]:
retail_sales = pd.read_sql('''
SELECT * 
FROM initial_data
''', conn,
parse_dates=['Date'])

retail_sales.head()

,Transaction_ID,Date,Customer_ID,Gender,Age,Product_Category,Quantity,Price_per_Unit,Total_Amount,month,day,month_val,day_val,Age_group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,November,Friday,11,4,26-35
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,February,Monday,2,0,26-35
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,January,Friday,1,4,46-55
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,May,Sunday,5,6,36-45
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,May,Saturday,5,5,26-35

In [71]:
# This section explores sales performance across revenue, product categories, customer demographics, and time-based trends.

In [72]:
# Revenue insights
total_revenue = retail_sales['Total_Amount'].sum()
average_order_val = retail_sales['Total_Amount'].mean()
largest_sale = retail_sales['Total_Amount'].max()

In [73]:
'''
Findings:

- Total revenue generated : 456000
- Average order value : 456
- Largest sale : 2000

'''

'\nFindings:\n\n- Total revenue generated : 456000\n- Average order value : 456\n- Largest sale : 2000\n\n'

In [74]:
# product insights
product_categories = retail_sales.groupby(['Product_Category'], as_index=False).agg(
    Total_revenue = ('Total_Amount', 'sum'),
    Total_quantity = ('Quantity', 'sum')
).sort_values(by='Total_revenue', ascending=False)

In [75]:
product_categories

  Product_Category  Total_revenue  Total_quantity
2      Electronics         156905             849
1         Clothing         155580             894
0           Beauty         143515             771

In [76]:
'''
Findings:

- Electronics generated the most revenue.
- Clothing sold the most quantity.

'''

'\nFindings:\n\n- Electronics generated the most revenue.\n- Clothing sold the most quantity.\n\n'

In [77]:
# Time insights
monthly = retail_sales.groupby(['month_val'], as_index=False).agg(
    revenue = ('Total_Amount', 'sum')
).sort_values(by='revenue', ascending=False).reset_index(drop=True)

daily = retail_sales.groupby(['day_val'], as_index=False).agg(
    revenue = ('Total_Amount', 'sum')
).sort_values(by='revenue', ascending=False).reset_index(drop=True)

In [78]:
monthly

    month_val  revenue
0           5    53150
1          10    46580
2          12    44690
3           2    44060
4           1    36980
5           8    36960
6           6    36715
7           7    35465
8          11    34920
9           4    33870
10          3    28990
11          9    23620

In [79]:
daily

   day_val  revenue
0        5    78815
1        0    70250
2        1    69440
3        4    66290
4        2    58770
5        6    58600
6        3    53835

In [80]:
'''
Findings:

- May generated highest revenue.
- Saturday generated highest revenue.
'''

'\nFindings:\n\n- May generated highest revenue.\n- Saturday generated highest revenue.\n'

In [81]:
retail_sales.head()

,Transaction_ID,Date,Customer_ID,Gender,Age,Product_Category,Quantity,Price_per_Unit,Total_Amount,month,day,month_val,day_val,Age_group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,November,Friday,11,4,26-35
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,February,Monday,2,0,26-35
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,January,Friday,1,4,46-55
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,May,Sunday,5,6,36-45
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,May,Saturday,5,5,26-35

In [82]:
# Customer insights
Gender = retail_sales.groupby(['Gender'], as_index=False).agg(
    Revenue = ('Total_Amount', 'sum'),
    Orders = ('Quantity', 'sum')
).sort_values(by='Revenue', ascending=False).reset_index(drop=True)

Age = retail_sales.groupby(['Age_group'], as_index=False).agg(
    Revenue = ('Total_Amount', 'sum'),
    Orders = ('Quantity', 'sum')
).sort_values(by='Revenue', ascending=False).reset_index(drop=True)

In [83]:
Gender

   Gender  Revenue  Orders
0  Female   232840    1298
1    Male   223160    1216

In [84]:
Age

  Age_group  Revenue  Orders
0     46-55   100690     588
1     26-35    98480     540
2     36-45    91870     506
3     18-25    84550     412
4       56+    80410     468

In [85]:
'''
Findings:

- There was not a significant difference between male and females interms of orders and sales.
- age group 46-55 had the highest sales but there is no clear outlier.
- Customer analysis was limited because each customer appeared once in the dataset.
'''

'\nFindings:\n\n- There was not a significant difference between male and females interms of orders and sales.\n- age group 46-55 had the highest sales but there is no clear outlier.\n- Customer analysis was limited because each customer appeared once in the dataset.\n'

In [86]:
# Trend patterns
trend = retail_sales.groupby(['month'], as_index=False).agg(
    quantity_pm = ('Total_Amount', 'sum')
).sort_values(by=['month'])

fig = px.line(trend, x="month", y="quantity_pm")
fig.show()

category_peak = retail_sales.groupby(['Product_Category', retail_sales['Date'].dt.month], as_index=False).agg(
    pm_revenue = ('Total_Amount', 'sum')
).sort_values(by='pm_revenue', ascending=False)

In [87]:
category_peak.head()

   Product_Category  Date  pm_revenue
28      Electronics     5       23245
35      Electronics    12       20220
33      Electronics    10       17910
16         Clothing     5       17455
6            Beauty     7       16090

In [88]:
'''
Findings:

- No strong seasonality identified due to the lack of historical data.
'''

'\nFindings:\n\n- No strong seasonality identified due to the lack of historical data.\n'

In [89]:
retail_sales

,Transaction_ID,Date,Customer_ID,Gender,Age,Product_Category,Quantity,Price_per_Unit,Total_Amount,month,day,month_val,day_val,Age_group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,November,Friday,11,4,26-35
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,February,Monday,2,0,26-35
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,January,Friday,1,4,46-55
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,May,Sunday,5,6,36-45
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,May,Saturday,5,5,26-35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,May,Tuesday,5,1,56+
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,November,Friday,11,4,46-55
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,October,Sunday,10,6,18-25
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,December,Tuesday,12,1,36-45
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,April,Wednesday,4,2,46-55

In [90]:
# Distribution / Outlier
quantity_dis = retail_sales[['Date', 'Quantity']]
distribution = retail_sales['Quantity'].value_counts()
category_sum = retail_sales.groupby(['Product_Category'], as_index=False).agg(
    Quantity_total = ('Quantity', 'sum'),
    revenue_total = ('Total_Amount', 'sum')
)

largest_orders = retail_sales.sort_values(
    by='Total_Amount',
    ascending=False
).head(10)[['Quantity', 'Total_Amount']]

In [91]:
retail_sales[['Quantity', 'Total_Amount']].describe()

          Quantity  Total_Amount
count  1000.000000   1000.000000
mean      2.514000    456.000000
std       1.132734    559.997632
min       1.000000     25.000000
25%       1.000000     60.000000
50%       3.000000    135.000000
75%       4.000000    900.000000
max       4.000000   2000.000000

In [92]:
largest_orders

     Quantity  Total_Amount
945         4          2000
71          4          2000
14          4          2000
576         4          2000
571         4          2000
268         4          2000
502         4          2000
926         4          2000
252         4          2000
546         4          2000

In [93]:
'''
Findings:
- Transactions were reviewd using summary statistics.
- No extreme values were identified.
- Quantity distribution was balanced.
- Revenue distribution was balanced accross all categories.

'''

'\nFindings:\n- Transactions were reviewd using summary statistics.\n- No extreme values were identified.\n- Quantity distribution was balanced.\n- Revenue distribution was balanced accross all categories.\n\n'

In [94]:
retail_sales

,Transaction_ID,Date,Customer_ID,Gender,Age,Product_Category,Quantity,Price_per_Unit,Total_Amount,month,day,month_val,day_val,Age_group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,November,Friday,11,4,26-35
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,February,Monday,2,0,26-35
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,January,Friday,1,4,46-55
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,May,Sunday,5,6,36-45
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,May,Saturday,5,5,26-35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,May,Tuesday,5,1,56+
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,November,Friday,11,4,46-55
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,October,Sunday,10,6,18-25
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,December,Tuesday,12,1,36-45
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,April,Wednesday,4,2,46-55

In [95]:
#sql queries

monthly_revenue = pd.read_sql('''
SELECT month_val, month, SUM(Total_Amount) as revenue
FROM initial_data
GROUP BY month_val, month
ORDER BY month_val ASC
                                     ''', conn)

category_revenue = pd.read_sql('''
SELECT Product_Category, SUM(Total_Amount) as revenue
FROM initial_data
GROUP BY Product_Category
ORDER BY revenue DESC                            
                             ''', conn)

Top_customers = pd.read_sql('''
SELECT Customer_ID, Total_Amount
FROM initial_data
ORDER BY Total_Amount DESC
LIMIT 10
                            ''', conn)

# Due to each customer appearing once, analysis was limited

gender_revenue = pd.read_sql('''
SELECT Gender, SUM(Total_Amount) as Revenue
FROM initial_data
GROUP BY Gender
ORDER BY Revenue DESC
                            ''', conn)

age_group_revenue = pd.read_sql('''
SELECT Age_group, SUM(Total_Amount) as Revenue
FROM initial_data
GROUP BY Age_group
ORDER BY Revenue DESC
                            ''', conn)

average_order_by_category = pd.read_sql('''
SELECT Product_Category, AVG(Quantity) as average_order
FROM initial_data
GROUP BY Product_Category
ORDER BY average_order DESC                                       
                                        ''', conn)

In [ ]:
'''
SQL Analysis:

Questions were answered about customer demographics, time based revenue trends, category performance and average order values.

Queries included:

- Monthly revenue trends
- Revenue by product category
- Top spending customers
- Revenue by gender
- Revenue by age group
- Average orders by product category

'''

In [97]:
retail_sales.to_csv('retail_sales_data.csv', index=False)